### ISSUE TITLE
PP: More message types

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/aosprotocol#14]
The protocol currently defines three message types:

Value | Type
-- | --
0 | CHAT_ALL
1 | CHAT_TEAM
2 | CHAT_SYSTEM

1.x expands this with

Value | Type
-- | --
0 | CHAT_ALL
1 | CHAT_TEAM
2 | CHAT_SYSTEM
3 | CHAT_BIG (displayed on the center of the screen)

In addition, OpenSpades defines:

Prefix | Meaning
--- | ---
N%: | Displays a "Notice" alert.
!%: | Displays a "Error" alert accompanied with a sound.
%%: | Displays a "Warning" alert accompanied with a sound.
C%: | Displays a center-aligned large message.

The prefixes are kind of ugly, so I propose the following extension:

Value | Type
-- | --
0 | CHAT_ALL
1 | CHAT_TEAM
2 | CHAT_SYSTEM
3 | CHAT_BIG (displayed on the center of the screen)
4 | CHAT_INFO (displays a notice)
5 | CHAT_WARNING (displays a warning)
5 | CHAT_ERROR (displays a error)

Concerns:
 - old clients might not support this. This can be easily solved with server-side version checking.

**Comment by xtreme8000** [comment]
Could you provide examples on how these new types should be displayed on screen?

**Comment by NotAFile** [comment]
I think that is up to the individual implementation. There's really no good way to standardize it, it has to fit with each games look and feel.

In OpenSpades, the following is used:

BIG: displayed in the upper half in large letters, usually message about the game state. E.g. X has captured the intel, You were killed by X.

INFO, WARNING, ERROR: Small popup box in the bottom half. Info has a black border, warning a yellow border + icon, error a red border + icon

**Comment by xtreme8000** [comment]
Maybe this could work like https://github.com/piqueserver/aosprotocol/issues/15#issuecomment-455909618 too?

**Comment by xtreme8000** [comment]
assigned extID 0xC1 (193, packetless), version 1 in BetterSpades
