### ISSUE TITLE
PP: Kick reason

### ISSUE THREAD

**Issue by xtreme8000** [piqueserver/aosprotocol#15]
~This might be useful for future extensions *(like increasing player limit)* that involve non backwards compatible changes. It would give the player a message about what exactly failed.~

~This would work by sending a `ChatMessage` packet before the `StateData` packet first, then closing the connection like usual.~

~EDIT: for voxlap this would just report back `Kicked`~

**Comment by xtreme8000** [comment]
This now works as follows as of https://github.com/xtreme8000/BetterSpades/commit/6d792407d26a43b931ea92607b6f808a83367835:

The server is supposed to sent its custom disconnect reason a few seconds before disconnect in a ChatMessage packet with `player_id=255` and `type=2 (system)`, which will be shown when the connection is reset on the client.
On clients not supporting this, it will be shown as a normal system message in chat, and the generic disconnect reason from enet payload will be shown.

**Comment by NotAFile** [comment]
what does the StateData refer to above? That's obsolete, right.

**Comment by xtreme8000** [comment]
> That's obsolete, right?

**yep**

**Comment by xtreme8000** [comment]
assigned extID `0xC2` (194, packetless), version `1` in BetterSpades
